#!/bin/bash
# If not running interactively, don't do anything #
[[ $- != *i* ]] && return

# Set Path VAR #
if [ -d "$HOME/.bin" ] ;
  then PATH="$HOME/.bin:$PATH"
fi
if [ -d "$HOME/.local/bin" ] ;
  then PATH="$HOME/.local/bin:$PATH"
fi

### Ignore Upper- and LowerCase when TAB Completion ###
bind "set completion-ignore-case on"

### MAN PAGE ###
# Integrate Most in Man
export PAGER=most
