#!/bin/bash

##################
### Main ALIAS ###
##################

# Nator Alias Help Page
alias help-alias="less ~/.nator-alias-help"

# List
alias ls="ls --color=auto"
alias la="ls -a --color=auto --time-style long-iso"
alias l="ls --color=auto -lA --time-style long-iso"
alias ll="ls --color=auto -la --time-style long-iso"
alias l.="ls -A | egrep '^\.'"

# Change Directory
alias cd..="cd .."
alias ..="cd .."
alias ...="cd ../../"
alias ....="cd ../../../"
alias .....="cd ../../../../"

# Find
alias ff="find / -name"
alias f="find . -name"

# Color Adjust
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"
alias ip="alias ip='ip -c'"
alias pacman="pacman --color auto"
alias pactree="pactree --color"
alias vdir="vdir --color=auto"
alias watch="watch --color"
#alias man="color function"

alias yay="sudo -u $USER yay"
#alias browser="midori &"

# Kali Undercover Mode
alias panic="kali-undercover"
alias ku="kali-undercover"
alias qwer="kali-undercover"

# PGAdmin4
alias pgadmin="sudo /usr/pgadmin4/bin/pgadmin4"

# Haskel Shortcut
alias haskel="ghci"

# CyberGhost
alias cyberghost="sudo cyberghostvpn --traffic --connect --country-code"
alias cyberghostlist="cyberghostvpn --traffic --country-code"

# Spotify - IF HDPI Setup
# alias spotifys="spotify --force-device-scale-factor=2.0 %U"

# VIM
alias vi="vim"

# Man Page - German Edition
alias man="LANG=de_DE.UTF-8 man"

#fix obvious typo's - ArcoLinux
alias cd..='cd ..'
alias pdw="pwd"
alias udpate='sudo pacman -Syyu'
alias upate='sudo pacman -Syyu'
alias updte='sudo pacman -Syyu'
alias updqte='sudo pacman -Syyu'
alias upqll="paru -Syu --noconfirm"
alias upal="paru -Syu --noconfirm"

# Aliases for software managment
# pacman or pm
alias pacman='sudo pacman --color auto'
alias update='sudo pacman -Syyu'

#pacman unlock
alias unlock="sudo rm /var/lib/pacman/db.lck"
alias rmpacmanlock="sudo rm /var/lib/pacman/db.lck"

#ps
alias psa="ps auxf"
alias psgrep="ps aux | grep -v grep | grep -i -e VSZ -e"

#grub update
alias update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg"

#add new fonts
alias update-fc='sudo fc-cache -fv'

#switch between bash and zsh
alias tobash="sudo chsh $USER -s /bin/bash && echo 'Now log out.'"
alias tozsh="sudo chsh $USER -s /bin/zsh && echo 'Now log out.'"

#switch between lightdm and sddm
alias tolightdm="sudo pacman -S lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings --noconfirm --needed ; sudo systemctl enable lightdm.service -f ; echo 'Lightm is active - reboot now'"
alias tosddm="sudo pacman -S sddm --noconfirm --needed ; sudo systemctl enable sddm.service -f ; echo 'Sddm is active - reboot now'"
alias togdm="sudo pacman -S gdm --noconfirm --needed ; sudo systemctl enable gdm.service -f ; echo 'GDM is active - reboot now'"

#hardware info --short
alias hw="hwinfo --short"

#check vulnerabilities microcode
alias microcode='grep . /sys/devices/system/cpu/vulnerabilities/*'


