#!/bin/bash
# If not running interactively, don't do anything #
[[ $- != *i* ]] && return

# Set Path VAR #
if [ -d "$HOME/.bin" ] ;
  then PATH="$HOME/.bin:$PATH"
fi
if [ -d "$HOME/.local/bin" ] ;
  then PATH="$HOME/.local/bin:$PATH"
fi

### Ignore Upper- and LowerCase when TAB Completion ###
bind "set completion-ignore-case on"


##################
### Main ALIAS ###
##################

#list
alias ls="ls --color=auto"
alias la="ls -a --color=auto --time-style long-iso"
alias l="ls --color=auto -lA --time-style long-iso"
alias ll="ls --color=auto -la --time-style long-iso"
alias l.="ls -A | egrep '^\.'"


alias cd..="cd .."
alias ..="cd .."
alias ...="cd ../../"
alias ....="cd ../../../"
alias .....="cd ../../../../"
alias ff="find / -name"
alias f="find . -name"
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"
alias ip="alias ip='ip -c'"
alias pacman="pacman --color auto"
alias pactree="pactree --color"
alias vdir="vdir --color=auto"
alias watch="watch --color"
alias man="color function"
alias yay="sudo -u norman yay"
alias browser="midori &"

# Kali Undercover Mode
alias panic="kali-undercover"
alias ku="kali-undercover"
alias qwer="kali-undercover"

# CUSTOM Additional ALIAS
alias pgadmin="sudo /usr/pgadmin4/bin/pgadmin4"
alias haskel="ghci"
alias cyberghost="sudo cyberghostvpn --traffic sudo cyberghostvpn --traffic --connect --country-code"
alias cyberghostlist="cyberghostvpn --traffic --country-code"
alias spotifys="spotify --force-device-scale-factor=2.0 %U"
alias vi="vim"

### MAN PAGE ###
# Integrate Most in Man
export PAGER=most

# German Man Page
alias man="LANG=de_DE.UTF-8 man"





